import Head from "next/head";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Prompts from "@/components/prompts";
import Input from "@/components/input";
import styled from "styled-components";
import Output from "@/components/output";
import SmallSidebar from "@/components/SmallSidebar";
import React from "react";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { Document, userState } from "@/recoil";
import { useRouter } from "next/router";
import { ask, getUser } from "@/recoil/functions";

const inter = Inter({ subsets: ["latin"] });

const DocumentRender: React.FC<{ documentId?: string; document?: Document }> = (
	props
) => {
	const { documentId, document } = props;
	const uid = useRecoilValue(userState).uid;
	const setUser = useSetRecoilState(userState);

	const [currentVersion, setCurrentVersion] = React.useState(0);

	const callbackAsk = React.useCallback(
		async (value) => {
			if (!uid) return;
			await ask(value, uid, documentId);
			const userData = await getUser(uid);

			setUser({
				_id: userData._id,
				uid: userData.uid,
				documents: userData.documents,
			});
		},
		[uid, documentId]
	);
	return (
		<>
			<Main className={`${inter.className}`}>
				<Sidebar active_id={documentId} />
				<Container>
					<Prompts list={document?.versions || []} />
					<Input onClick={callbackAsk} />
				</Container>
				<Output version_id={document?.versions[currentVersion]?._id} />
				<SmallSidebar
					active_version={currentVersion}
					versions_count={document?.versions?.length || 1}
					onSelect={setCurrentVersion}
				/>
			</Main>
		</>
	);
};

export default function DocumentPage() {
	const doc_id = useRouter().query.id as string;
	const documents = useRecoilValue(userState).documents;
	console.log(documents);

	const document = documents.find((doc) => doc._id === doc_id);
	if (!document) {
		return <div>Document not found</div>;
	}

	return (
		<>
			<Head>
				<title>Framer Ai</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DocumentRender documentId={doc_id} document={document} />
		</>
	);
}

const Main = styled.div`
	display: grid;
	grid-template-columns: 256px 4fr 5fr 70px;
`;

const Container = styled.div`
	display: flex;
	height: 100vh;
	flex-direction: column;
	justify-content: space-between;
	box-sizing: border-box;
	padding: 8px;
`;
